<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class ciudades extends Seeder
{
public function run(): void
    {
        DB::table('ciudades')->insert([
            ['nombre' => 'A Coruña'],
            ['nombre' => 'Vitoria-Gasteiz'],
            ['nombre' => 'Albacete'],
            ['nombre' => 'Alcalá de Henares'],
            ['nombre' => 'Alcobendas'],
            ['nombre' => 'Alcoy'],
            ['nombre' => 'Alcorcón'],
            ['nombre' => 'Algeciras'],
            ['nombre' => 'Alicante'],
            ['nombre' => 'Almería'],
            ['nombre' => 'Antequera'],
            ['nombre' => 'Arona'],
            ['nombre' => 'Arrecife'],
            ['nombre' => 'Ávila'],
            ['nombre' => 'Avilés'],
            ['nombre' => 'Badajoz'],
            ['nombre' => 'Badalona'],
            ['nombre' => 'Barcelona'],
            ['nombre' => 'Benidorm'],
            ['nombre' => 'Bilbao'],
            ['nombre' => 'Burgos'],
            ['nombre' => 'Cáceres'],
            ['nombre' => 'Cádiz'],
            ['nombre' => 'Cambrils'],
            ['nombre' => 'Cartagena'],
            ['nombre' => 'Castellón de la Plana'],
            ['nombre' => 'Ceuta'],
            ['nombre' => 'Chiclana de la Frontera'],
            ['nombre' => 'Ciudad Real'],
            ['nombre' => 'Collado Villalba'],
            ['nombre' => 'Córdoba'],
            ['nombre' => 'Cornellà de Llobregat'],
            ['nombre' => 'Coslada'],
            ['nombre' => 'Cuenca'],
            ['nombre' => 'Denia'],
            ['nombre' => 'Donostia / San Sebastián'],
            ['nombre' => 'Dos Hermanas'],
            ['nombre' => 'El Ejido'],
            ['nombre' => 'El Prat de Llobregat'],
            ['nombre' => 'El Puerto de Santa María'],
            ['nombre' => 'Elche'],
            ['nombre' => 'Elda'],
            ['nombre' => 'Estepona'],
            ['nombre' => 'Ferrol'],
            ['nombre' => 'Figueres'],
            ['nombre' => 'Fuengirola'],
            ['nombre' => 'Fuenlabrada'],
            ['nombre' => 'Gandía'],
            ['nombre' => 'Getafe'],
            ['nombre' => 'Gijón'],
            ['nombre' => 'Girona'],
            ['nombre' => 'Granadilla de Abona'],
            ['nombre' => 'Granada'],
            ['nombre' => 'Guadalajara'],
            ['nombre' => 'Huelva'],
            ['nombre' => 'Huesca'],
            ['nombre' => 'Igualada'],
            ['nombre' => 'Jaén'],
            ['nombre' => 'Jerez de la Frontera'],
            ['nombre' => 'La Laguna (San Cristóbal de La Laguna)'],
            ['nombre' => 'La Línea de la Concepción'],
            ['nombre' => 'La Nucía'],
            ['nombre' => 'La Orotava'],
            ['nombre' => 'La Rinconada'],
            ['nombre' => 'La Roda'],
            ['nombre' => 'Las Palmas de Gran Canaria'],
            ['nombre' => 'Leganés'],
            ['nombre' => 'León'],
            ['nombre' => 'Lepe'],
            ['nombre' => 'Linares'],
            ['nombre' => 'Lleida'],
            ['nombre' => 'Logroño'],
            ['nombre' => 'Lorca'],
            ['nombre' => 'Los Palacios y Villafranca'],
            ['nombre' => 'Lugo'],
            ['nombre' => 'L\'Hospitalet de Llobregat'],
            ['nombre' => 'Madrid'],
            ['nombre' => 'Majadahonda'],
            ['nombre' => 'Málaga'],
            ['nombre' => 'Manacor'],
            ['nombre' => 'Manresa'],
            ['nombre' => 'Marbella'],
            ['nombre' => 'Maspalomas (San Bartolomé de Tirajana)'],
            ['nombre' => 'Mataró'],
            ['nombre' => 'Melilla'],
            ['nombre' => 'Mérida'],
            ['nombre' => 'Mijas'],
            ['nombre' => 'Molina de Segura'],
            ['nombre' => 'Montcada i Reixac'],
            ['nombre' => 'Móstoles'],
            ['nombre' => 'Murcia'],
            ['nombre' => 'Ourense'],
            ['nombre' => 'Oviedo'],
            ['nombre' => 'Palencia'],
            ['nombre' => 'Palma'],
            ['nombre' => 'Pamplona / Iruña'],
            ['nombre' => 'Parla'],
            ['nombre' => 'Paterna'],
            ['nombre' => 'Pontevedra'],
            ['nombre' => 'Reus'],
            ['nombre' => 'Rivas-Vaciamadrid'],
            ['nombre' => 'Roquetas de Mar'],
            ['nombre' => 'Rubí'],
            ['nombre' => 'Sabadell'],
            ['nombre' => 'Sagunto'],
            ['nombre' => 'Salamanca'],
            ['nombre' => 'Salou'],
            ['nombre' => 'San Fernando'],
            ['nombre' => 'San Sebastián de los Reyes'],
            ['nombre' => 'Sanlúcar de Barrameda'],
            ['nombre' => 'Santa Coloma de Gramenet'],
            ['nombre' => 'Santa Cruz de Tenerife'],
            ['nombre' => 'Santa Lucía de Tirajana'],
            ['nombre' => 'Santander'],
            ['nombre' => 'Santiago de Compostela'],
            ['nombre' => 'Segovia'],
            ['nombre' => 'Sevilla'],
            ['nombre' => 'Siero'],
            ['nombre' => 'Soria'],
            ['nombre' => 'Talavera de la Reina'],
            ['nombre' => 'Tarragona'],
            ['nombre' => 'Telde'],
            ['nombre' => 'Terrassa'],
            ['nombre' => 'Teruel'],
            ['nombre' => 'Toledo'],
            ['nombre' => 'Tomelloso'],
            ['nombre' => 'Torrejón de Ardoz'],
            ['nombre' => 'Torremolinos'],
            ['nombre' => 'Torrente'],
            ['nombre' => 'Torrevieja'],
            ['nombre' => 'Utrera'],
            ['nombre' => 'Valdemoro'],
            ['nombre' => 'Valencia'],
            ['nombre' => 'Valladolid'],
            ['nombre' => 'Vigo'],
            ['nombre' => 'Vila-real'],
            ['nombre' => 'Viladecans'],
            ['nombre' => 'Vilanova i la Geltrú'],
            ['nombre' => 'Vitoria-Gasteiz'],
            ['nombre' => 'Zamora'],
            ['nombre' => 'Zaragoza'],
        ]);
    }
}