<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class pelicula extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('pelicula')->insert([
            [
                'id' => 1,
                'adult' => false,
                'backdrop_ruta' => '/rthMuZfFv4fqEU4JVbgSW9wQ8rs.jpg',
                'id_api' => 986056,
                'lenguaje_original' => 'en',
                'titulo_original' => 'Thunderbolts*',
                'sinopsis' => 'Un grupo de supervillanos y antihéroes van en misiones para el gobierno. Basado en la serie de cómics del mismo nombre.',
                'poster_ruta' => '/zLbhKNJGDSfBCXFNtypM7ZuPTaW.jpg',
                'fecha_estreno' => '2025-04-30',
                'titulo' => 'Thunderbolts*',
                'video' => false,
                'duracion' => 120,
                'puntuacion_promedio' => 7.5,
                'numero_votos' => 1500,
                'popularidad' => 123.45,
                'activa' => true,
                'estreno' => true,
                'created_at' => Carbon::parse('2025-06-05 14:55:01'),
            ],
            [
                'id' => 2,
                'adult' => false,
                'backdrop_ruta' => '/fTrQsdMS2MUw00RnzH0r3JWHhts.jpg',
                'id_api' => 1197306,
                'lenguaje_original' => 'en',
                'titulo_original' => 'A Working Man',
                'sinopsis' => 'Levon Cade dejó atrás una condecorada carrera militar en las operaciones encubiertas para vivir una vida sencilla trabajando en la construcción. Pero cuando la hija de su jefe, que para él es como de la familia, es secuestrada por traficantes de personas, su búsqueda para traerla a casa descubre un mundo de corrupción mucho mayor de lo que jamás podría haber imaginado.',
                'poster_ruta' => '/oCsn3MV3QOJWnGVCb8B8VWrX5Qp.jpg',
                'fecha_estreno' => '2025-03-26',
                'titulo' => 'A Working Man',
                'video' => false,
                'duracion' => 95,
                'puntuacion_promedio' => 6.8,
                'numero_votos' => 500,
                'popularidad' => 55.67,
                'activa' => true,
                'estreno' => true,
                'created_at' => Carbon::parse('2025-06-05 14:55:01'),
            ],
            [
                'id' => 4,
                'adult' => false,
                'backdrop_ruta' => '/2Nti3gYAX513wvhp8IiLL6ZDyOm.jpg',
                'id_api' => 950387,
                'lenguaje_original' => 'en',
                'titulo_original' => 'A Minecraft Movie',
                'sinopsis' => 'Cuatro inadaptados se encuentran luchando con problemas ordinarios cuando de repente se ven arrastrados a través de un misterioso portal al Mundo Exterior: un extraño país de las maravillas cúbico que se nutre de la imaginación. Para volver a casa, tendrán que dominar este mundo mientras se embarcan en una búsqueda mágica con un inesperado experto artesano, Steve.',
                'poster_ruta' => '/mFjtmmh4RtK9tLv1aPnUsl6st3m.jpg',
                'fecha_estreno' => '2025-03-31',
                'titulo' => 'Una película de Minecraft',
                'video' => false,
                'duracion' => 90,
                'puntuacion_promedio' => 7.2,
                'numero_votos' => 1200,
                'popularidad' => 150.1,
                'activa' => true,
                'estreno' => true,
                'created_at' => Carbon::parse('2025-06-05 14:55:01'),
            ],
            [
                'id' => 6,
                'adult' => false,
                'backdrop_ruta' => '/bVm6udIB6iKsRqgMdQh6HywuEBj.jpg',
                'id_api' => 1233069,
                'lenguaje_original' => 'de',
                'titulo_original' => 'Exterritorial',
                'sinopsis' => 'Cuando su hijo desaparece en un consulado de EE. UU., una exsoldado de las fuerzas especiales hará lo imposible por encontrarlo... y destapará una oscura conspiración.',
                'poster_ruta' => '/7tWkxxiqraVx1IzYd4DHv6FIvhS.jpg',
                'fecha_estreno' => '2025-04-29',
                'titulo' => 'Extraterritorial',
                'video' => false,
                'duracion' => 98,
                'puntuacion_promedio' => 7.1,
                'numero_votos' => 650,
                'popularidad' => 75.8,
                'activa' => true,
                'estreno' => true,
                'created_at' => Carbon::parse('2025-06-05 14:55:01'),
            ],
            [
                'id' => 7,
                'adult' => false,
                'backdrop_ruta' => '/7Zx3wDG5bBtcfk8lcnCWDOLM4Y4.jpg',
                'id_api' => 552524,
                'lenguaje_original' => 'en',
                'titulo_original' => 'Lilo & Stitch',
                'sinopsis' => 'La conmovedora y divertidísima historia de una solitaria niña hawaiana y el extraterrestre fugitivo que la ayuda a reparar su desestructurada familia.',
                'poster_ruta' => '/mKKqV23MQ0uakJS8OCE2TfV5jNS.jpg',
                'fecha_estreno' => '2025-05-17',
                'titulo' => 'Lilo y Stitch',
                'video' => false,
                'duracion' => 108,
                'puntuacion_promedio' => 7.052,
                'numero_votos' => 467,
                'popularidad' => 605.7405,
                'activa' => true,
                'estreno' => false,
                'created_at' => Carbon::parse('2025-06-05 16:59:34'),
            ],
            [
                'id' => 9,
                'adult' => false,
                'backdrop_ruta' => '/v67tbCB03CMcJRWit8CS7JdJp6.jpg',
                'id_api' => 757725,
                'lenguaje_original' => 'en',
                'titulo_original' => 'Shadow Force',
                'sinopsis' => 'Con una recompensa por sus cabezas, la pareja formada por Omar Sy y Kerry Washington, huye con su hijo para escapar de su antigua organización: una unidad de operaciones en la sombra que ha sido enviada para liquidarlos.',
                'poster_ruta' => '/uX6FaNE86a4Xnf1mFFEryvjqB1D.jpg',
                'fecha_estreno' => '2025-05-01',
                'titulo' => 'Shadow Force',
                'video' => false,
                'duracion' => 103,
                'puntuacion_promedio' => 6.2,
                'numero_votos' => 36,
                'popularidad' => 323.5466,
                'activa' => true,
                'estreno' => false,
                'created_at' => Carbon::parse('2025-06-05 16:59:39'),
            ],
            [
                'id' => 12,
                'adult' => false,
                'backdrop_ruta' => '/icFWIk1KfkWLZnugZAJEDauNZ94.jpg',
                'id_api' => 1232546,
                'lenguaje_original' => 'en',
                'titulo_original' => 'Until Dawn',
                'sinopsis' => 'Un año después de la misteriosa desaparición de su hermana Melanie, Clover y sus amigas se dirigen al remoto valle donde desapareció en busca de respuestas. Mientras exploran un centro de visitantes abandonado, son acechadas por un asesino enmascarado que las mata una a una de forma horrible… para después despertar y encontrarse de nuevo al principio de la misma noche.',
                'poster_ruta' => '/exgfubqSbF4veI4uXFOdbV66gEf.jpg',
                'fecha_estreno' => '2025-04-23',
                'titulo' => 'Until Dawn',
                'video' => false,
                'duracion' => 103,
                'puntuacion_promedio' => 6.496,
                'numero_votos' => 570,
                'popularidad' => 160.4802,
                'activa' => true,
                'estreno' => false,
                'created_at' => Carbon::parse('2025-06-05 16:59:45'),
            ],
            [
                'id' => 15,
                'adult' => false,
                'backdrop_ruta' => '/uIpJPDNFoeX0TVml9smPrs9KUVx.jpg',
                'id_api' => 574475,
                'lenguaje_original' => 'en',
                'titulo_original' => 'Final Destination Bloodlines',
                'sinopsis' => 'Acosada por una violenta pesadilla recurrente, la estudiante universitaria Stefanie se dirige a casa para localizar a la única persona que podría ser capaz de romper el ciclo y salvar a su familia de la espeluznante muerte que inevitablemente les espera a todos.',
                'poster_ruta' => '/frNkbclQpexf3aUzZrnixF3t5Hw.jpg',
                'fecha_estreno' => '2025-05-14',
                'titulo' => 'Destino final: Lazos de sangre',
                'video' => false,
                'duracion' => 110,
                'puntuacion_promedio' => 7.0,
                'numero_votos' => 577,
                'popularidad' => 248.1093,
                'activa' => true,
                'estreno' => false,
                'created_at' => Carbon::parse('2025-06-06 10:58:19'),
            ],
            [
                'id' => 18,
                'adult' => false,
                'backdrop_ruta' => '/pOR4Aye28KLZ5Jogu8zc3yiqBpT.jpg',
                'id_api' => 1397832,
                'lenguaje_original' => 'es',
                'titulo_original' => 'La viuda negra',
                'sinopsis' => 'Cuando un hombre aparece muerto, la investigación del caso desbarata la imagen perfecta de su esposa y pone al descubierto su doble vida en este thriller basado en hechos reales.',
                'poster_ruta' => '/uuabL0qp3zygLDEjImbPiWR9j2e.jpg',
                'fecha_estreno' => '2025-05-29',
                'titulo' => 'La viuda negra',
                'video' => false,
                'duracion' => 120,
                'puntuacion_promedio' => 6.4,
                'numero_votos' => 69,
                'popularidad' => 128.6301,
                'activa' => true,
                'estreno' => false,
                'created_at' => Carbon::parse('2025-06-05 16:59:50'),
            ],
            [
                'id' => 19,
                'adult' => false,
                'backdrop_ruta' => '/tyfO9jHgkhypUFizRVYD0bytPjP.jpg',
                'id_api' => 447273,
                'lenguaje_original' => 'en',
                'titulo_original' => 'Snow White',
                'sinopsis' => 'Tras la desaparición del benévolo Rey, la Reina Malvada dominó la otrora bella tierra con una vena cruel. La princesa Blancanieves huye del castillo cuando la Reina, celosa de su belleza interior, intenta matarla. En lo profundo del oscuro bosque, se topa con siete enanos mágicos y un joven bandido llamado Jonathan. Juntos, luchan por sobrevivir a la implacable persecución de la Reina y aspiran a recuperar el reino en el proceso.',
                'poster_ruta' => '/sm91FNDF6OOKU4hT9BDW6EMoyDB.jpg',
                'fecha_estreno' => '2025-03-12',
                'titulo' => 'Blancanieves',
                'video' => false,
                'duracion' => 99,
                'puntuacion_promedio' => 4.29,
                'numero_votos' => 1011,
                'popularidad' => 136.7444,
                'activa' => true,
                'estreno' => false,
                'created_at' => Carbon::parse('2025-06-05 16:59:51'),
            ],
            [
                'id' => 21,
                'adult' => false,
                'backdrop_ruta' => '/lAnkMSDISzMYLWICS7m16rSTUHD.jpg',
                'id_api' => 1011477,
                'lenguaje_original' => 'en',
                'titulo_original' => 'Karate Kid: Legends',
                'sinopsis' => 'Tras una tragedia familiar, el prodigio del kung fu Li Fong se ve obligado a abandonar su hogar en Pekín y trasladarse a Nueva York con su madre. Cuando un nuevo amigo necesita su ayuda, Li se presenta a una competición de kárate, pero sus habilidades no son suficientes. El profesor de kung fu de Li, el Sr. Han, pide ayuda al Karate Kid original, Daniel LaRusso, y Li aprende una nueva forma de luchar, fusionando sus dos estilos en uno solo para el enfrentamiento definitivo de artes marciales.',
                'poster_ruta' => '/efNhiZPk71FTYJ30dBkWMfc939D.jpg',
                'fecha_estreno' => '2025-05-08',
                'titulo' => 'Karate Kid: Legends',
                'video' => false,
                'duracion' => 94,
                'puntuacion_promedio' => 7.2,
                'numero_votos' => 74,
                'popularidad' => 98.5296,
                'activa' => true,
                'estreno' => false,
                'created_at' => Carbon::parse('2025-06-05 16:59:54'),
            ],
            [
                'id' => 23,
                'adult' => false,
                'backdrop_ruta' => '/op3qmNhvwEvyT7UFyPbIfQmKriB.jpg',
                'id_api' => 324544,
                'lenguaje_original' => 'de',
                'titulo_original' => 'In the Lost Lands',
                'sinopsis' => 'Basada en el relato de George R. R. Martin. Una reina (Amara Okereke), desesperada por encontrar la felicidad en el amor, envía a la poderosa bruja Gray Alys (Milla Jovovich) a las Tierras Perdidas, en busca de un poder mágico que permite a una persona transformarse en un hombre lobo. Con el misterioso cazador Boyce (Dave Bautista), que la apoya en la lucha contra criaturas oscuras y despiadadas, Gray deambula por un mundo inquietante y peligroso. Pero solo ella sabe que, cada deseo que se concede, tiene consecuencias inimaginables.',
                'poster_ruta' => '/sLDxndoqFWwJEq7iEdYQBzPjUDQ.jpg',
                'fecha_estreno' => '2025-02-27',
                'titulo' => 'Tierras perdidas',
                'video' => false,
                'duracion' => 102,
                'puntuacion_promedio' => 6.347,
                'numero_votos' => 413,
                'popularidad' => 109.3352,
                'activa' => true,
                'estreno' => false,
                'created_at' => Carbon::parse('2025-06-05 16:59:55'),
            ],
        ]);
    }
}
